Traceback (most recent call last):
  File "/Users/apple/Desktop/DataEngineeringBootCamp/GithubProfile/jackie-yt-wang/scripts/update_weather.py", line 30, in <module>
    temperature = weather_data['current']['temp']
                  ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'current'
ent call last):
  File "/Users/apple/Desktop/DataEngineeringBootCamp/GithubProfile/jackie-yt-wang/scripts/update_weather.py", line 30, in <module>
    temperature = weather_data['current']['temp']
                  ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'current'
PYTHON RUNNING FAILED
[ERROR:] RETURN CODE:  1
[ERROR:] REFER TO THE LOG FOR THE REASON FOR THE FAILURE.
